// <auto-generated />
using System;
using Leave_Management_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Leave_Management_System.Migrations
{
    [DbContext(typeof(DBContextLeaveManagement))]
    partial class DBContextLeaveManagementModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Leave_Management_System.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "IT",
                            FullName = "Asma SGHIR",
                            JoiningDate = new DateTime(2025, 4, 22, 18, 57, 8, 301, DateTimeKind.Local).AddTicks(6747)
                        },
                        new
                        {
                            Id = 2,
                            Department = "MECA",
                            FullName = "John Doee",
                            JoiningDate = new DateTime(2025, 4, 22, 18, 57, 8, 301, DateTimeKind.Local).AddTicks(6785)
                        },
                        new
                        {
                            Id = 3,
                            Department = "Auto",
                            FullName = "aLEX aLEX",
                            JoiningDate = new DateTime(2025, 4, 22, 18, 57, 8, 301, DateTimeKind.Local).AddTicks(6787)
                        });
                });

            modelBuilder.Entity("Leave_Management_System.Entities.LeaveRequests", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeaveType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("LeaveRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 4, 22, 18, 57, 8, 301, DateTimeKind.Local).AddTicks(7223),
                            EmployeeId = 1,
                            EndDate = new DateTime(2025, 4, 27, 18, 57, 8, 301, DateTimeKind.Local).AddTicks(7221),
                            LeaveType = 0,
                            Reason = "Vacation",
                            StartDate = new DateTime(2025, 4, 22, 18, 57, 8, 301, DateTimeKind.Local).AddTicks(7218),
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 4, 22, 18, 57, 8, 301, DateTimeKind.Local).AddTicks(7229),
                            EmployeeId = 2,
                            EndDate = new DateTime(2025, 4, 26, 18, 57, 8, 301, DateTimeKind.Local).AddTicks(7227),
                            LeaveType = 1,
                            Reason = "Vacation",
                            StartDate = new DateTime(2025, 4, 22, 18, 57, 8, 301, DateTimeKind.Local).AddTicks(7226),
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 4, 22, 18, 57, 8, 301, DateTimeKind.Local).AddTicks(7235),
                            EmployeeId = 3,
                            EndDate = new DateTime(2025, 4, 26, 18, 57, 8, 301, DateTimeKind.Local).AddTicks(7233),
                            LeaveType = 2,
                            Reason = "Vacation",
                            StartDate = new DateTime(2025, 4, 22, 18, 57, 8, 301, DateTimeKind.Local).AddTicks(7231),
                            Status = 2
                        });
                });

            modelBuilder.Entity("Leave_Management_System.Entities.LeaveRequests", b =>
                {
                    b.HasOne("Leave_Management_System.Entities.Employee", "Employee")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Leave_Management_System.Entities.Employee", b =>
                {
                    b.Navigation("LeaveRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
